spring:
  application:
    name: oauth2_login
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile,email
            redirect-uri: ${HOST}/login/oauth2/code/google
            # client-name: Google
        #   github:
        #     client-id: ${GITHUB_CLIENT_ID}
        #     client-secret: ${GITHUB_CLIENT_SECRET}
  data:
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
      timeout: 60000
  cache:
    redis:
      time-to-live: 1800
server:
  port: 4500
  servlet:
    session:
      cookie:
        http-only: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
