name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      PORT: ${{ vars.PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Redis container
        run: |
          docker pull redis
          docker run -d --name redis-server -p 6379:6379 redis

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -DPRIVATE_KEY_PEM="${{ secrets.PRIVATE_KEY_PEM }}" -DPORT=$PORT --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
